#!/usr/bin/env bash
# =============================================================================
# setup-entra-app.sh — Entra app-registration changes for AUTH_MODE=entra
#
# DO NOT run this script without reviewing it first.
# It modifies an existing Azure AD app registration.
#
# Prerequisites:
#   - az CLI logged in as a Global Administrator or Application Administrator
#   - The app registration already exists (was used for MCP_OAUTH_ENABLED path)
#   - jq installed
#
# Usage:
#   TENANT_ID=<tenant-id> APP_OBJECT_ID=<object-id> bash setup-entra-app.sh
#
# To find APP_OBJECT_ID:
#   az ad app list --display-name "<your-app-name>" --query "[].id" -o tsv
# =============================================================================

set -euo pipefail

TENANT_ID="${TENANT_ID:?Set TENANT_ID to your Entra tenant GUID}"
APP_OBJECT_ID="${APP_OBJECT_ID:?Set APP_OBJECT_ID to your app registration object ID (not client ID)}"

# The Microsoft Enterprise Token Store — used by Cowork to inject credentials
VAULT_CLIENT_ID="ab3be6b7-f5df-413d-ac2d-abf1e3fd9c0b"
TEAMS_REDIRECT_URI="https://teams.microsoft.com/api/platform/v1.0/oAuthConsentRedirect"

echo "=== Entra app registration setup for AUTH_MODE=entra ==="
echo "Tenant:     $TENANT_ID"
echo "App Object: $APP_OBJECT_ID"
echo ""

# ---------------------------------------------------------------------------
# Step 1: Get the Application ID URI (generated by Teams Developer Portal)
# You must have already completed the Teams Dev Portal SSO registration and
# have the Application ID URI it generated.
# ---------------------------------------------------------------------------
APP_ID_URI="${APP_ID_URI:?Set APP_ID_URI to the Application ID URI from Teams Developer Portal SSO registration}"

echo ">>> 1. Adding Application ID URI: $APP_ID_URI"
CURRENT_URIS=$(az ad app show --id "$APP_OBJECT_ID" --query "identifierUris" -o tsv)
echo "    Current identifierUris: $CURRENT_URIS"

# Append the new URI (preserve existing ones)
az ad app update \
  --id "$APP_OBJECT_ID" \
  --identifier-uris "$CURRENT_URIS $APP_ID_URI" \
  --verbose

echo "    Done."

# ---------------------------------------------------------------------------
# Step 2: Add Teams OAuth consent redirect URI to the Web platform
# ---------------------------------------------------------------------------
echo ""
echo ">>> 2. Adding redirect URI: $TEAMS_REDIRECT_URI"

# Fetch existing web redirect URIs
EXISTING_REDIRECTS=$(az ad app show --id "$APP_OBJECT_ID" \
  --query "web.redirectUris" -o json)

echo "    Current redirect URIs: $EXISTING_REDIRECTS"

# Build updated list (jq append, deduplicate)
UPDATED_REDIRECTS=$(echo "$EXISTING_REDIRECTS" | \
  jq --arg new "$TEAMS_REDIRECT_URI" '. + [$new] | unique')

az ad app update \
  --id "$APP_OBJECT_ID" \
  --web-redirect-uris $(echo "$UPDATED_REDIRECTS" | jq -r '.[]') \
  --verbose

echo "    Done."

# ---------------------------------------------------------------------------
# Step 3: Pre-authorise the Enterprise Token Store as a client application
# This allows Cowork to obtain tokens for your API on behalf of users.
# ---------------------------------------------------------------------------
echo ""
echo ">>> 3. Pre-authorising Enterprise Token Store client ($VAULT_CLIENT_ID)"
echo "    NOTE: This step uses Microsoft Graph directly (az ad app update"
echo "    does not expose preAuthorizedApplications). You may need to do this"
echo "    manually in the Entra admin center: App registrations → your app →"
echo "    Expose an API → Add a client application → enter $VAULT_CLIENT_ID →"
echo "    select all scopes → Authorize."
echo ""
echo "    Attempting via Graph API patch..."

CLIENT_ID=$(az ad app show --id "$APP_OBJECT_ID" --query "appId" -o tsv)
echo "    Client (application) ID: $CLIENT_ID"

# Get the scope ID for the existing access_as_user scope (or any scope)
SCOPE_ID=$(az ad app show --id "$APP_OBJECT_ID" \
  --query "api.oauth2PermissionScopes[0].id" -o tsv 2>/dev/null || echo "")

if [ -z "$SCOPE_ID" ]; then
  echo "    WARNING: No oauth2PermissionScopes found on this app."
  echo "    Create a scope (e.g. 'access_as_user') in the Entra admin center first,"
  echo "    then re-run this script."
else
  echo "    Using scope ID: $SCOPE_ID"

  PATCH_BODY=$(cat <<EOF
{
  "api": {
    "preAuthorizedApplications": [
      {
        "appId": "$VAULT_CLIENT_ID",
        "delegatedPermissionIds": ["$SCOPE_ID"]
      }
    ]
  }
}
EOF
)

  az rest \
    --method PATCH \
    --uri "https://graph.microsoft.com/v1.0/applications/$APP_OBJECT_ID" \
    --headers "Content-Type=application/json" \
    --body "$PATCH_BODY"

  echo "    Done."
fi

# ---------------------------------------------------------------------------
# Step 4: Print environment variables to set on the Container App
# ---------------------------------------------------------------------------
echo ""
echo "=== Container App environment variables to set ==="
echo ""
echo "AUTH_MODE=entra"
echo "ENTRA_TENANT_ID=$TENANT_ID"
echo "ENTRA_AUDIENCE=$APP_ID_URI"
echo "ENTRA_ALLOWED_CLIENT_IDS=$VAULT_CLIENT_ID"
echo ""
echo "Set these with:"
echo "  az containerapp update \\"
echo "    --name ca-tc-mcp-connectwise \\"
echo "    --resource-group rg-tc-mcp-prod \\"
echo "    --set-env-vars AUTH_MODE=entra ENTRA_TENANT_ID=$TENANT_ID ENTRA_AUDIENCE=\"$APP_ID_URI\" ENTRA_ALLOWED_CLIENT_IDS=$VAULT_CLIENT_ID"
echo ""
echo "=== Done. Review the above output before proceeding. ==="
